name: Build And Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:  
  schedule:
    - cron: "00 16 * * *"  
env:
  TZ: Asia/Shanghai
jobs:
  build-project:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install and Build
        run: |
          npm ci
          npm run build    
          
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT 
          
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true  
      
      - name: Commit project ğŸ±â€ğŸ
        if: steps.verify_diff.outputs.changed == 'true'
        run: | 
          git config --local user.email "28900094+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "HeFung"
          git add .
          git commit -m "bing wallpaper project Update: `TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S'`"

      - name: Push project ğŸš€
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_DOCS }}
          branch: main 
